version: '3.8'
services:
  tg_bot:
    build: tg_bot
    volumes:
      - ./data_base:/app/data
    env_file:
      - .env
  web:
    build: app
    ports:
      - "80:8000"
    restart: unless-stopped
    volumes:
      - ./data_base:/app/data
    env_file:
      - .env
